### ISSUE TITLE
Unnecessary complexity?

### ISSUE THREAD

**Issue by michaelshire** [redhat-cop/gitops-catalog#17]
In this script:
https://github.com/redhat-canada-gitops/catalog/blob/master/sealed-secrets-operator/scripts/get-sealed-secret-key.sh

You have:
`oc get $(oc get secret -n sealed-secrets -l sealedsecrets.bitnami.com/sealed-secrets-key=active -o name) -n sealed-secrets -o yaml >  ~/.bitnami/sealed-secrets-secret.yaml`

You can use the label in the outer command like this to get the same results:
`oc get secret -l sealedsecrets.bitnami.com/sealed-secrets-key=active -n sealed-secrets -o yaml >  ~/.bitnami/sealed-secrets-secret.yaml`

**Comment by adetalhouet** [comment]
Provided a fix
