### ISSUE TITLE
`patchesJson6902` and `patchesStrategicMerge` Depreciated

### ISSUE THREAD

**Issue by strangiato** [redhat-cop/gitops-catalog#208]
`patchesJson6902` and `patchesStrategicMerge` have been depreciated in the v1beta1 API in [kustomize v5.0.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0) and should be replaced by `patches`.

Any references using these should be updated in the GitOps catalog.

**Comment by codekow** [comment]
#213 should address this issue
