### ISSUE TITLE
`bases` depreciated

### ISSUE THREAD

**Issue by strangiato** [redhat-cop/gitops-catalog#209]
The `bases` resource has been depreciated since [v2.1.0](https://github.com/kubernetes-sigs/kustomize/blob/aa46b6ec44dfbff16b8b925f1db4913fdba04a85/docs/fields.md#bases) and should be combined/replaced with `resources`.

Any references using `bases` in the gitops catalog should be updated to utilize `resources`.

**Comment by codekow** [comment]
#213 should address this issue
