### ISSUE TITLE
cert manager operator inconsistent namespace

### ISSUE THREAD

**Issue by dlbewley** [redhat-cop/gitops-catalog#238]
The namespace field in base/kustomization.yaml should be updated to match the namespace.yaml resource (`cert-manager-operator`).

https://github.com/redhat-cop/gitops-catalog/blob/main/cert-manager-operator/operator/base/kustomization.yaml

I believe the startingCSV field in the base/subscription.yaml is superfluous and may be removed.

**Comment by adetalhouet** [comment]
Thank you for pointing this out.
