### ISSUE TITLE
Should the maven pipelines task default to a Red Hat image?

### ISSUE THREAD

**Issue by gnunn1** [redhat-cop/gitops-catalog#52]
Right now the maven pipelines task (https://github.com/redhat-cop/gitops-catalog/blob/main/openshift-pipelines-tasks/maven/base/maven-task.yaml#L8) is using a google image from the google registry, I would like to suggest we default this to a Red Hat image. I have been using the `java:openjdk-11-ubi8` image in OpenShift and haven't experienced any issues.

Interestingly my m2-cache overlay is expecting this image to be used and does not work with the google image. So if you want to leave the google image as the default I need to either make the overlay work with it, patch the overlay to use the RH image or just remove the overlay completely. 

@pittar and @sabre1041 thoughts?

**Comment by gnunn1** [comment]
Created PR #53

**Comment by pittar** [comment]
Thanks.  I'll give it a shot when I do my next cluster rebuild in a day or two!

**Comment by pittar** [comment]
PR was merged a while back.  Forgot to close the issue.
