### ISSUE TITLE
Rename "elastisearch-operator" to "elasticsearch-operator"

### ISSUE THREAD

**Issue by pittar** [redhat-cop/gitops-catalog#56]
As per part 2 of https://github.com/redhat-cop/gitops-catalog/pull/55 , the main Elasticsearch operator folder is missing a `c` in its name.

@gnunn1 @sabre1041 , what's the best way to fix the folder name without breaking anyone's existing kustomizations?

**Comment by adetalhouet** [comment]
This has been fixed here https://github.com/redhat-cop/gitops-catalog/commit/66f503f2be9071457283637e7945f33f16b886b1

**Comment by strangiato** [comment]
Resolved by #96.  Can we close this issue?
