### ISSUE TITLE
Finalizers in PVCs

### ISSUE THREAD

**Issue by strangiato** [redhat-cop/gitops-catalog#79]
Several PVC objects have a finalizer included in the object.  Generally I keep all finalizers out of the object defenition and only allow k8s to apply the appropriate finalizers in order to prevent a finalizer that doesn't exist from preventing the deletion of the object.

Is there any advantage to keeping the finalizer in the object definition?

```
finalizers:
    - kubernetes.io/pvc-protection
 ```

**Comment by pittar** [comment]
These aren't required and should be removed.

**Comment by adetalhouet** [comment]
Provided a fix
