### ISSUE TITLE
Remove olm.providedAPIs from OperatorGroups

### ISSUE THREAD

**Issue by strangiato** [redhat-cop/gitops-catalog#81]
`olm.providedAPIs` on OperatorGroup objects should be applied by OLM and should not be included in the object definition.

```
olm.providedAPIs
```

Example:

rhsso/rhsso-operator/base/rhsso-operatorgroup.yaml

**Comment by pittar** [comment]
The rhsso dir should be removed altogether.  It was based on an early version of the operator (which wasn't very good).

As we find other OperatorGroups that have this issue, we should remove them.
